import { Product, DeliveryZone } from '@/types';

export const siteConfig = {
  name: "Ashla Kids",
  shortName: "Ashla Kids",
  tagline: "Boutique & Vente en Gros et Détail pour Enfants à Dakar",
  slogan: "Habillez leurs plus beaux moments avec style et douceur.",
  description: "Boutique enfant de référence à Dakar (Sénégal). Prêt-à-porter filles et garçons, chaussures & baskets tendance, robes de cérémonie, sacs de maternelle, bérets et layette bébé. Vente en gros & au détail avec livraison express partout au Sénégal.",
  url: "https://ashlakids.sn",
  email: "ndiayassaitou1995@gmail.com",
  phonePrimary: "+221 77 108 98 63",
  phoneSecondary: "+221 78 121 63 23",
  whatsappMain: "+221771089863",
  whatsappRaw: "221771089863",
  location: {
    city: "Dakar",
    country: "Sénégal",
    address: "Dakar, Sénégal — Livraison à domicile & Expéditions nationales",
    hours: "Lundi au Samedi : 09h00 - 20h00 · Dimanche sur permanence",
  },
  social: {
    facebook: "https://facebook.com/ashlakids",
    instagram: "https://instagram.com/ashla_kids",
    snapchat: "https://snapchat.com/add/Ashla_style",
  },
  payments: ["Wave", "Orange Money", "Free Money", "Espèces à la livraison"],
  
  categories: [
    { id: "chaussures", label: "Chaussures & Baskets", icon: "Footprints", count: "Pointures 21 à 36", tagColor: "bg-[#FFF0F3] text-[#FF3864]" },
    { id: "vetements", label: "Ensembles & Prêt-à-porter", icon: "Shirt", count: "3 mois à 10 ans", tagColor: "bg-[#FFF9E6] text-[#B78103]" },
    { id: "ceremonie", label: "Robes & Cérémonies", icon: "Sparkles", count: "Modèles Princesse", tagColor: "bg-[#E8F8F5] text-[#1E9589]" },
    { id: "sacs-accessoires", label: "Sacs & Bérets 3D", icon: "Backpack", count: "Maternelle & Mode", tagColor: "bg-[#EFF6FF] text-[#2563EB]" },
    { id: "gros-puériculture", label: "Gros, Bébés & Layette", icon: "Package", count: "Tarifs revendeurs", tagColor: "bg-[#F3E8FF] text-[#7E22CE]" },
  ],

  deliveryZones: [
    { area: "Dakar Ville (Plateau, Point E, Fann, Médina)", price: 1500, timeframe: "Dans la journée (2-4h)" },
    { area: "Grand Dakar (Almadies, Ngor, Ouakam, Yoff)", price: 2000, timeframe: "Dans la journée" },
    { area: "Banlieue (Guédiawaye, Pikine, Rufisque, Keur Massar)", price: 2500, timeframe: "24h chrono" },
    { area: "Régions du Sénégal (Thiès, Saint-Louis, Mbour, Touba...)", price: 3000, timeframe: "Expédition Express 24-48h" },
  ] as DeliveryZone[],

  products: [
    {
      id: "baskets-retro-classic",
      name: "Baskets Rétro Suède & Mesh",
      category: "chaussures",
      price: 9000,
      priceOptions: [
        { label: "Pointures 23 à 30", price: 9000 },
        { label: "Pointures 31 à 36", price: 10000 },
      ],
      image: "/images/products/baskets-retro-collection.jpg",
      badge: "Coup de cœur Rentrée",
      sizes: ["23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36"],
      colors: ["Blanc épuré", "Rose poudré", "Rouge dynamique", "Jaune moutarde"],
      isPopular: true,
      isNewArrival: true,
      description: "Baskets tendance rétro bicolores avec semelle souple antidérapante. Parfaites pour l'école, le sport et les sorties du week-end.",
      features: ["Mesh respirant & suède velours", "Lacets confortables et ajustement anatomique", "Semelle gomme amortissante"],
    },
    {
      id: "derbies-ville-cuir",
      name: "Chaussures de Ville & Cérémonie en Cuir",
      category: "chaussures",
      price: 7500,
      priceOptions: [
        { label: "Pointures 26 à 30", price: 7500 },
        { label: "Pointures 31 à 36", price: 8500 },
      ],
      image: "/images/products/derbies-ville-cuir.jpg",
      badge: "Élégance & Fêtes",
      sizes: ["26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36"],
      colors: ["Noir habillé", "Marron chocolat"],
      isPopular: true,
      description: "Chaussures richelieu/derbies au style classique et distingué. Idéales pour compléter un costume, une tenue d'école chic ou un mariage.",
      features: ["Cuir synthétique verni haute durabilité", "Semelle crantée tout-terrain", "Fermeture à lacets renforcés"],
    },
    {
      id: "sandales-gladiateur-ete",
      name: "Sandales Gladiateur Confort Multi-Boucles",
      category: "chaussures",
      price: 7500,
      image: "/images/products/sandales-gladiateur.jpg",
      badge: "Must-Have Été",
      sizes: ["21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
      colors: ["Noir", "Blanc écru", "Marron caramel", "Argenté miroir"],
      description: "Sandales ouvertes à lanières ajustables. Semelle anatomique moelleuse assurant un maintien idéal du pied toute la journée.",
      features: ["3 boucles réglables sur le coup-de-pied", "Semelle première confort matelassée", "Fermeture bride cheville sécurisée"],
    },
    {
      id: "robe-princesse-tulle-nœud",
      name: "Robe de Cérémonie Princesse à Grand Nœud",
      category: "ceremonie",
      price: 13500,
      originalPrice: 16000,
      image: "/images/products/robe-princesse-noeud-dos.jpg",
      badge: "Prestige Cérémonie",
      sizes: ["1-2 ans", "3-4 ans", "5-6 ans", "7-8 ans"],
      colors: ["Bleu ciel féerique", "Rose bonbon", "Blanc pur"],
      isPopular: true,
      isNewArrival: true,
      description: "Magnifique robe évasée en tulle brodé et dentelle festonnée, rehaussée d'un grand nœud satiné dans le dos. Pour mariages, baptêmes et anniversaires.",
      features: ["Doublure 100% coton douce sur la peau", "Fermeture éclair invisible dorsale", "Juponnage volumineux intégré"],
    },
    {
      id: "robe-chemisier-blanche",
      name: "Robe Chemisier Chic & Jupon Évasé",
      category: "vetements",
      price: 10000,
      image: "/images/products/robe-chemisier-blanche.jpg",
      badge: "Tendance 2026",
      sizes: ["2 ans", "3 ans", "4 ans", "5 ans", "6 ans"],
      colors: ["Blanc immaculé & gilet terracotta"],
      isPopular: true,
      description: "Ensemble chemisier blanc col classique avec coupe trapèze plissée et gilet sans manches assorti. Style parisien raffiné.",
      features: ["Coton doux haute densité", "Boutonnage perlé complet", "Facile d'entretien"],
    },
    {
      id: "ensemble-duo-chemisier-gilet",
      name: "Duo Chemisier & Pull Tricot Sans Manches",
      category: "vetements",
      price: 10000,
      image: "/images/products/ensemble-duo-chemisier.jpg",
      badge: "Collection Duo",
      sizes: ["2 ans", "3 ans", "4 ans", "5 ans", "6 ans"],
      colors: ["Bleu pastel / Gilet ivoire", "Blanc / Gilet marron"],
      description: "Ensemble deux pièces combinant une robe chemise à manches ballon et un débardeur en maille fine extensible.",
      features: ["2 pièces détachables et combinables", "Maille tricotée hypoallergénique", "Coupe fluide et élégante"],
    },
    {
      id: "ensemble-jean-blouse-rayee",
      name: "Ensemble Blouse Volantée & Jean Fashion",
      category: "vetements",
      price: 10000,
      image: "/images/products/ensemble-jean-blouse-rayee.jpg",
      badge: "Best-Seller",
      sizes: ["1 an", "2 ans", "3 ans", "4 ans", "5 ans", "6 ans"],
      colors: ["Rayé bleu & Denim indigo"],
      isPopular: true,
      description: "Haut en rayures fines avec manches évasées à volants, associé à un pantalon jean travaillé avec laçages latéraux contrastés.",
      features: ["Jean extensible avec taille élastiquée", "Blouse légère et aérée", "Finition soignée des bordures"],
    },
    {
      id: "sac-maternelle-mickey-minnie",
      name: "Sac à Dos Maternelle Matelassé Disney",
      category: "sacs-accessoires",
      price: 8000,
      image: "/images/products/sac-mickey-minnie.jpg",
      badge: "Spécial Maternelle",
      sizes: ["Taille unique crèche & maternelle"],
      colors: ["Crème & Rose poudré (Mickey/Minnie)", "Bleu marine (Mickey/Pluto)"],
      isPopular: true,
      isNewArrival: true,
      description: "Le sac à dos parfait pour la crèche et la maternelle. Matelassage en vagues ultra-léger, bretelles renforcées et poche frontale zippée.",
      features: ["Tissu matelassé imperméabilisé et lavable", "Compartiment principal pour cahier A5, doudou et goûter", "Poignées doubles porté main ou dos"],
    },
    {
      id: "sac-maternelle-mickey-pluto",
      name: "Sac à Dos Marine Mickey & Pluto",
      category: "sacs-accessoires",
      price: 8000,
      image: "/images/products/sac-mickey-pluto.jpg",
      badge: "Nouveauté",
      sizes: ["Taille unique crèche & maternelle"],
      colors: ["Bleu marine"],
      description: "Version garçons et filles en bleu nuit profond avec grand écusson relief Mickey & Pluto. Robuste et spacieux pour l'école.",
      features: ["Fermetures zippées fluides adaptées aux petites mains", "Dos moussé respirant", "Poches latérales pour gourde"],
    },
    {
      id: "berets-fleurs-3d-pastel",
      name: "Béret Doux Hiver à Fleurs 3D en Relief",
      category: "sacs-accessoires",
      price: 4500,
      image: "/images/products/berets-fleurs-pastel.jpg",
      badge: "Accessoire Star",
      sizes: ["1 à 8 ans (Élastique)"],
      colors: ["Lilas", "Écru vanille", "Rose dragée", "Rouge brique", "Jaune soleil"],
      description: "L'accessoire couture qui sublime n'importe quelle tenue d'enfant. Laine douce tricotée agrémentée de jolies fleurs pelucheuses en 3D.",
      features: ["Laine douce anti-grattage", "Tour de tête souple et extensible", "Fleurs feutrées cousues main"],
    },
  ] as Product[],

  features: [
    {
      title: "Gros & Détail",
      desc: "Vente à l'unité pour vos enfants ou par lots avantageux pour les revendeurs et boutiques.",
      icon: "Boxes",
    },
    {
      title: "Livraison Express Dakar",
      desc: "Réception de vos colis le jour même à Dakar et expédition rapide dans toutes les régions.",
      icon: "Truck",
    },
    {
      title: "Paiement Simple & Sécurisé",
      desc: "Réglez vos commandes facilement par Wave, Orange Money ou en espèces à la livraison.",
      icon: "ShieldCheck",
    },
    {
      title: "Conseils Tailles & Pointures",
      desc: "Notre équipe WhatsApp vous guide en direct pour choisir la pointure ou la taille exacte.",
      icon: "Sparkles",
    },
  ],

  testimonials: [
    {
      name: "Fatou D.",
      location: "Almadies, Dakar",
      comment: "Les baskets rétro sont magnifiques et très solides ! Mon fils les porte pour l'école tous les jours. Livraison rapide reçue le jour même par Wave.",
      rating: 5,
    },
    {
      name: "Mariama S.",
      location: "Sacré-Cœur 3, Dakar",
      comment: "J'ai commandé la robe de princesse en tulle pour les 3 ans de ma fille. La qualité du tissu et la doublure en coton sont parfaites. Bravo Ashla Kids !",
      rating: 5,
    },
    {
      name: "Awa B.",
      location: "Mermoz, Dakar",
      comment: "Super service client sur WhatsApp ! Ils m'ont conseillé la bonne pointure en direct avec une vidéo de la semelle. Sac Mickey adorable.",
      rating: 5,
    },
  ],
};
